// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA489PGgrJrI58PiRqWhBiMqtGbLceafoc',
    appId: '1:35514532026:android:c88f6aa4a7bfb1b4250283',
    messagingSenderId: '35514532026',
    projectId: 'bus-tracker-8cb2c',
    storageBucket: 'bus-tracker-8cb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonQe43diNzGl1oz4zmXQXMcpF2qvM13M',
    appId: '1:35514532026:ios:fa928aa929820eaa250283',
    messagingSenderId: '35514532026',
    projectId: 'bus-tracker-8cb2c',
    storageBucket: 'bus-tracker-8cb2c.firebasestorage.app',
    iosBundleId: 'com.example.busTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Tiu5ADEqPtfK0gmQMUWYpS3NX8-iiR4',
    appId: '1:35514532026:web:a241fb46a932f0dd250283',
    messagingSenderId: '35514532026',
    projectId: 'bus-tracker-8cb2c',
    authDomain: 'bus-tracker-8cb2c.firebaseapp.com',
    storageBucket: 'bus-tracker-8cb2c.firebasestorage.app',
    measurementId: 'G-S7KPXF2YK2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Tiu5ADEqPtfK0gmQMUWYpS3NX8-iiR4',
    appId: '1:35514532026:web:a241fb46a932f0dd250283',
    messagingSenderId: '35514532026',
    projectId: 'bus-tracker-8cb2c',
    authDomain: 'bus-tracker-8cb2c.firebaseapp.com',
    storageBucket: 'bus-tracker-8cb2c.firebasestorage.app',
    measurementId: 'G-S7KPXF2YK2',
  );

}